[tool.black]
line-length = 120
target-version = ['py36']
skip-string-normalization = true

[tool.isort]
profile = "black"

[tool.mypy]
show_error_codes = true

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"

[[tool.mypy.overrides]]
module = ["lzo", "posix_ipc", "setuptools"]
ignore_missing_imports = true
