name: Build PR Branch

on:
  push:
    paths-ignore:
      - README.md
      - .gitignore
    branches-ignore:
      - main
  pull_request:
    types:
      - opened

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          cache: 'pip'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install liblzo2-dev
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Execute linters
        run: |
          pylint -v --rcfile=.pylintrc *.py homcc tests
          mypy -v --pretty *.py homcc
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          cache: 'pip'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install liblzo2-dev
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Execute format-check
        uses: psf/black@stable
        with:
          options: "--check --color --diff --verbose"
      - name: Execute isort
        uses: isort/isort-action@master
        with:
          configuration: "--check --color --diff --gitignore --verbose"
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          cache: 'pip'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install liblzo2-dev
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest -v -rfE --cov=homcc --capture=tee-sys
  vera-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Veracode SCA Scan
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        run: curl -sSL https://download.sourceclear.com/ci.sh | sh -s -- scan --loud --allow-dirty --scm-ref v${{ env.RELEASE_VERSION }} --scm-ref-type branch

