name: Build Branch

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install packaging dependencies # see https://github.com/astraw/stdeb/issues/175
        run: |
          sudo apt install -y \
            python3 python3-dev python3-pip python3-venv python3-all \
            dh-python debhelper devscripts dput software-properties-common \
            python3-distutils python3-setuptools python3-wheel python3-stdeb
      - name: Install further Python dependencies
        run: |
          python3 -m pip install -r requirements.txt 
      - name: Build
        run: |
          make all
      - name: Upload .deb packages
        uses: actions/upload-artifact@v3
        with: 
          name: homcc_debian_packages
          path: target/
          if-no-files-found: error