name: Pull Request CI

# TODO(s.pirsch): change to pull_request
on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '^3.6'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: python -m pytest -v
  lints:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '^3.6'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Execute linters
        # TODO(s.pirsch): replace wildcards
        run: |
          pylint -v --rcfile=.pylintrc *.py **/*.py
          mypy -v *.py **/*.py
      - name: Execute format-check
        uses: psf/black@stable
        with:
          options: "--check --color --diff --verbose"
